### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by oli44** [eisbehr-/node-red-counter#1]
Hi there,

I have trouble installing your tool. Here is the message:

> npm install node-red-contrib-counter
> 
> npm WARN unmet dependency /home/olivier/.node-red/node_modules/node-red-contrib-osc/node_modules/osc/node_modules/serialport/node_modules/node-pre-gyp/node_modules/tar-pack requires debug@'~2.2.0' but will load
> 
> npm WARN unmet dependency /home/olivier/.node-red/node_modules/node-red-contrib-osc/node_modules/osc/node_modules/serialport/node_modules/debug,
> npm WARN unmet dependency which is version 2.3.3
> 
> node-red-contrib-counter@0.1.3 node_modules/node-red-contrib-counter

In case it helps, here is my node-red console at start:
`node-red`

> Welcome to Node-RED
> ===================
> 
> 24 Nov 09:54:34 - [info] Node-RED version: v0.15.2
> 24 Nov 09:54:34 - [info] Node.js  version: v0.12.10
> 24 Nov 09:54:34 - [info] Linux 3.16.0-77-generic x64 LE
> 24 Nov 09:54:35 - [info] Loading palette nodes
> 24 Nov 09:54:47 - [warn] ------------------------------------------------------
> 24 Nov 09:54:47 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
> 24 Nov 09:54:47 - [warn] ------------------------------------------------------
> 24 Nov 09:54:47 - [info] Settings file  : /home/olivier/.node-red/settings.js
> 24 Nov 09:54:47 - [info] User directory : /home/olivier/.node-red
> 24 Nov 09:54:47 - [info] Flows file     : /home/olivier/.node-red/flows_lenouveau.json
> 24 Nov 09:54:48 - [info] Starting flows
> 24 Nov 09:54:48 - [info] [udp out:oscarito] udp ready: 192.168.1.68:2016
> 24 Nov 09:54:48 - [info] Started flows
> 24 Nov 09:54:48 - [info] Server now running at http://127.0.0.1:1880/

Running on Linux Mint 17 64bit

**Comment by eisbehr-** [comment]
Hello @oli44,

this seems not a problem of my module, it seems other modules of yours have some problems, It always told that `node-red-contrib-osc` seems to be involved. And even your start of `node-red` seems to be fine.

And the message `node-red-contrib-counter@0.1.3 node_modules/node-red-contrib-counter` tell that my module is installed correct. So are you sure there is no `counter` node in your node-red after start?

**Comment by oli44** [comment]
Thanks for your quik feedback.  'node-red-conrib-osc' works fine although it complains a lot. 

Well the counter stays unknown when i copy paste one of your examples. If i filter the nodes using counter keyword, result stays empty

**Comment by eisbehr-** [comment]
Are you sure you executed the install command in the correct directory then? It has to be in the correct structure for node-red. Otherwise try to install it globally with `npm install - g node-red-contrib-counter`, what worked for me too.

**Comment by oli44** [comment]
Yep! Worked for me too, thx for your help, gummieisbehr

**Comment by eisbehr-** [comment]
Great! You're welcome!
