### ISSUE TITLE
More a feature request.

### ISSUE THREAD

**Issue by Just-another-pleb** [eisbehr-/node-red-counter#18]
An option so when you set an `upper` and `lower` limits, it loops between them when either is reached.
Rather than just going (eg)
1 2 3 4 5 5 5 5 5 5 5
or
9 8 7 6 5 4 3 3 3 3 3 3

It would go:
1 2 3 4 5 1 2 3 4 5 1 2 3 4 5
and so on.

**Comment by dkern** [comment]
I don't see an general usecase here, but this is pretty easy to do in other ways. Just use a second node and reset the counter when the limit is reached. I don't think i would add that to the node.

**Comment by Just-another-pleb** [comment]
It was a passing comment.   Not a demand.

I already use a node as you suggested.
