### ISSUE TITLE
Optional upper and lower limits for a counter

### ISSUE THREAD

**Issue by bbboki** [eisbehr-/node-red-counter#2]
Hi, I like counter node you shared with us:-)
It would be great to improve this counter, to be more generic and easily reusable in some real life scenarios...

It would be great that counter can be given upper and lower limits (with +/-inf as defaults).
If upper/lower is set, counter should count only within a range limited with upper/lower.
Upon upper/lower limit is reached, it should be indicated to other nodes. For example, msg.upperLimitReached and msg.lowerLimitReached should be present and equal to true.
This will imply that if "Output="split": two additional outputs would need to be present, but msg to particular output to be emitted only if particular limit is reached.

Thank you.

**Comment by eisbehr-** [comment]
Hello @bbboki,

that could be usefull. I will think about this ...

Thanks!

**Comment by eisbehr-** [comment]
Added in version 0.1.4!
