### ISSUE TITLE
initial value cant be update

### ISSUE THREAD

**Issue by yikfhong** [eisbehr-/node-red-counter#3]
hi,
can make the initial value ability to be update by input?so i can make counter starting increase synchronize to the slider.

**Comment by eisbehr-** [comment]
You can set the current value with `msg.reset`. If you don't pass in a number, the counter will be reset to the initiali value. If you give the `reset` a number, the counter will be reset to this.

For example: `msg.reset = 5;` will reset the actual value of the counter to `5`.
