### ISSUE TITLE
decrement not working

### ISSUE THREAD

**Issue by Alush2121** [eisbehr-/node-red-counter#5]
Hi,
i copied and paste the nodes, but the decrements is increasing instead of decreasing.
Alush

**Comment by eisbehr-** [comment]
Hello @Alush2121,

if you report a problem, please add as many details as you could. I don't know where you have the problem and what you have configured. Please provice an example flow and I will take a look. Actually I can't see any problem here ...

**Comment by Alush2121** [comment]
Good morning,

I was using a different counter. Removed it and installed
node-red-conrtib-counter and it worked. Sorry for any inconvenience.


Thank you,
Alush

**Comment by eisbehr-** [comment]
Okay, glad everything is fine!
