### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by linuxtrap** [eisbehr-/node-red-counter#6]
Could you implement a way to set initial value?

Initial Count: The initial count get a value from a file or other easy way to store last value.
msg.initialcount: The Initial count will be set with the value given from the payload.

Best Regards
PerT

**Comment by eisbehr-** [comment]
Hello @linuxtrap 

You can use `msg.reset` for this:
_msg.reset: resets the counter to it's initial count, or to the given value, when it's a number._
