### ISSUE TITLE
Not all NPM version information has updated to 0.1.5

### ISSUE THREAD

**Issue by cymplecy** [eisbehr-/node-red-counter#9]
On https://flows.nodered.org/node/node-red-contrib-counter some info says 0.1.4 - some says 0.1.5 and it says it hasn't been updated for > 1 year

Something not quite right there

**Comment by cymplecy** [comment]
All Ok now

**Comment by eisbehr-** [comment]
Hello @cymplecy 

The problem belongs to the node-red page itself. They have an own repo list and the updates there may take some time. This happen on every update, as far as I experienced so far. ;)

**Comment by cymplecy** [comment]
Ta for info :)
